name: CI/CD Test

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
      
      - name: Test Next.js app
        run: npm test

      - name: Simulate Deployment
        run: |
          echo "Deployment simulated!"
      
      - name: Complete
        run: |
          echo "CI/CD pipeline completed!"